[package]
name = "event-state-choice-mismatch"
version = "0.1.0"
edition = "2021"
publish = false

[build-dependencies]
touchportal-sdk = { version = "0.0.1", path = "../../sdk" }
serde_json = "1.0.142"

