[package]
name = "touchportal-actions-no-lines"
version = "0.1.0"
edition = "2021"
publish = false

[build-dependencies]
touchportal-sdk = { version = "0.1.0", path = "../../sdk" }
serde_json = "1.0.142"
